### ISSUE TITLE
Integrate Website Pages and Ensure Seamless Navigation

### ISSUE THREAD

**Issue by akshit-g** [GDSC-UPES/GDSC-UPES-Website#14] opened 2023-10-02 20:42 UTC
Integrate all the developed website pages, ensuring seamless navigation and consistent design and functionality across the entire website. This issue involves linking different sections, implementing navigation menus, and conducting thorough testing to guarantee a cohesive user experience.

Integrate all developed pages into the website's navigation structure. Ensure that users can navigate between pages smoothly using menu items, buttons, or links.
Implement a consistent navigation menu/header across all pages, allowing users to access different sections of the website effortlessly.

Implement internal links within pages for smooth scrolling or jumping to specific sections. Ensure that these links work correctly and provide a seamless user experience.

**Comment by hustlerZzZ** [comment] 2023-10-03 01:43
Can you please assign this to me? I can easily do this.
Thanks and Regards

**Comment by rohin079** [comment] 2023-10-03 02:42
> Can you please assign this to me? I can easily do this. Thanks and Regards

Sure @hustlerZzZ

**Comment by Kairu-22** [comment] 2024-01-18 08:10
I would like to work on this, is the issue still open to work on?

**Comment by hustlerZzZ** [comment] 2024-01-18 08:14
> I would like to work on this, is the issue still open to work on?
> 

Heyy, the issue is fixed and merged 😊

**Closed** 2024-01-20 10:56 UTC
Labels: hacktoberfest
